ext {
    artifactId = 'async-service-bus'
    artifactDescription = 'Async Service Bus'
}

dependencies {
    api project(":async-commons-api")
    api project(":domain-events-api")
    api project(":async-commons")

    implementation 'com.azure:azure-core:1.49.1'
    implementation 'com.azure:azure-messaging-servicebus:7.17.1'
    implementation 'com.azure.resourcemanager:azure-resourcemanager:2.40.0'
    implementation group: 'com.microsoft.azure', name: 'azure-servicebus', version: '3.6.7'

    compileOnly 'io.projectreactor:reactor-core'
    api 'com.fasterxml.jackson.core:jackson-databind'
    testImplementation 'io.projectreactor:reactor-test'

    compile("org.springframework.boot:spring-boot-starter-log4j2")

}
